- name: 'ALL'
  clouds:
  - name: 'Amazon'
    regions: ['us-west-1', 'us-west-2', 'us-east-1', 'eu-west-1',
              'ap-southeast-1', 'ap-northeast-1', 'ap-southeast-2',
              'sa-east-1']
  - name: 'Joyent'
    regions: ['us-west-1', 'us-east-1', 'us-sw-1', 'eu-ams-1']
  - name: 'Google'
    regions: ['us-central1', 'europe-west1', 'asia-east1']
