- name: 'UBUNTU_1404'
  platform: 'UNIX'
  architecture: 'I64'
  clouds:
  - name: 'Amazon'
    regions:
    - name: 'us-west-1'
      image_id: 'ami-cf6f7f8a'
    - name: 'us-west-2'
      image_id: 'ami-b1f8af81'
    - name: 'us-east-1'
      image_id: 'ami-06c4586e'
    - name: 'eu-west-1'
      image_id: 'ami-4043f337'
    - name: 'ap-southeast-1'
      image_id: 'ami-c5426f97'
    - name: 'ap-northeast-1'
      image_id: 'ami-08dfd809'
    - name: 'ap-southeast-2'
      image_id: 'ami-ef355cd5'
    - name: 'sa-east-1'
      image_id: 'ami-938a3b8e'
  - name: 'Joyent'
    regions:
    - name: 'us-west-1'
      image_id: '5f67e820-1489-4db7-9df2-1d8e3ec5cd90'
    - name: 'us-east-1'
      image_id: '5f67e820-1489-4db7-9df2-1d8e3ec5cd90'
    - name: 'us-sw-1'
      image_id: '5f67e820-1489-4db7-9df2-1d8e3ec5cd90'
    - name: 'eu-ams-1'
      image_id: '5f67e820-1489-4db7-9df2-1d8e3ec5cd90'
  - name: 'Google'
    regions:
    - name: 'us-central1'
      image_id: 'debian-cloud_debian-7-wheezy-v20150226'
    - name: 'europe-west1'
      image_id: 'debian-cloud_debian-7-wheezy-v20150226'
    - name: 'asia-east1'
      image_id: 'debian-cloud_debian-7-wheezy-v20150226'
- name: 'UBUNTU_TRUSTY'
  platform: 'UNIX'
  architecture: 'I64'
  clouds:
  - name: 'Amazon'
    regions:
    - name: 'us-west-1'
      image_id: 'ami-736e6536'
    - name: 'eu-west-1'
      image_id: 'ami-12345678'
  - name: 'Joyent'
    regions:
    - name: 'us-east-1'
      image_id: 'a6daab3317bf490e95a866854a7045d1'
    - name: 'us-sw-1'
      image_id: '8304fb5bac5242fc91bc00f44a1b4af4'
