- name: 'ALL'
  clouds:
  - name: 'Amazon'
    sizes: [ 't1.micro', 'm3.medium', 'm3.large', 'm3.xlarge', 'm3.2xlarge', 'm1.small', 'm1.medium', 'm1.large', 'm1.xlarge', 'c3.large', 'c3.xlarge',
             'c3.2xlarge', 'c3.4xlarge', 'c3.8xlarge', 'c1.medium', 'c1.xlarge', 'm2.xlarge', 'm2.2xlarge', 'm2.4xlarge']
  - name: 'Joyent'
    sizes: [ 'g3-highio-15-kvm', 'g3-highio-30-kvm', 'g3-highcpu-4-kvm', 'g3-highcpu-8-kvm', 'g3-highcpu-7-kvm',
             'g3-highcpu-1.75-kvm', 'g3-standard-1-kvm', 'g3-standard-2-kvm', 'g3-standard-8-kvm', 'g3-standard-4-kvm', 'g3-standard-7.5-kvm',
             'g3-standard-30-kvm', 'g3-standard-3.75-kvm', 'g3-standard-15-kvm', 'g3-standard-1.75-kvm',
             'g3-highstorage-32-kvm', 'g3-highmemory-68.375-kvm', 'g3-highmemory-34.25-kvm', 'g3-highmemory-17.125-kvm', 'g3-highio-60.5-kvm' ]
  - name: 'Google'
    sizes: [ 'n1-standard-16', 'n1-highcpu-8', 'n1-standard-8', 'n1-highcpu-4', 'n1-highmem-16', 'n1-standard-4', 'f1-micro', 'n1-standard-2',
             'n1-standard-1', 'n1-highmem-2', 'n1-highmem-4', 'n1-highcpu-16', 'n1-highcpu-2', 'n1-highmem-8', 'g1-small']

